image: docker-registry.praguebest.cz:5000/node-vuestorefront:latest

variables:
    GIT_BRANCH: master
    BUILD_CACHE_DIR_BASE: /pbs-deploy/docker-build/$CI_PROJECT_NAMESPACE/$CI_PROJECT_PATH
    BUILD_CACHE_DIR_PROD: $BUILD_CACHE_DIR_BASE/prod
    APP_SUBPATH: app
    DEPLOY_TARGET: $DEPLOY_SERVER:$DEPLOY_DIRECTORY/$APP_SUBPATH
    DEPLOY_LINKABLE_PATH_PREFIX: app_source
    DEPLOY_LINKABLE_PATH: ${DEPLOY_LINKABLE_PATH_PREFIX}__${CI_PIPELINE_ID}
    DEPLOY_LINKABLE_DIRECTORY: $DEPLOY_DIRECTORY/$DEPLOY_LINKABLE_PATH
    DEPLOY_LINKABLE_TARGET: $DEPLOY_SERVER:$DEPLOY_LINKABLE_DIRECTORY
    
stages:
    - copy
    - build

runCopy:
    stage: copy
    interruptible: true 
    variables:
        GIT_STRATEGY: none
    before_script:
        - set -eux
        - rm --force --recursive $BUILD_CACHE_DIR_PROD
        - mkdir --parents "$BUILD_CACHE_DIR_BASE"
        - eval $(ssh-agent -s)
        - ssh-add - <<< "${GITLAB_DEPLOY_GROUP_SYLIUS_SSH_KEY}"
        - ssh-keyscan "${DEPLOY_SERVER}" > /etc/ssh/ssh_known_hosts # to avoid "Host key verification failed." rsync/ssh error
    script:
        - git clone --branch "$GIT_BRANCH" --depth 1 https://foo:glpat-km9-__dg5K2HBs2r3PnA@gitlab.praguebest.cz/sylius/v_storefront.git "$BUILD_CACHE_DIR_PROD"
        - cd $BUILD_CACHE_DIR_PROD
        - ssh deployserver@$DEPLOY_SERVER "mkdir "${DEPLOY_LINKABLE_DIRECTORY}""
        - rsync -rpKzl --ignore-errors --force "." "deployserver@"$DEPLOY_LINKABLE_TARGET"" 2>&1
    # UNCOMMENT BELOW:
    # only:
    #     variables:
    #         - $CI_COMMIT_REF_NAME == $GIT_BRANCH
            
    tags:
        # runner has to be enabled https://gitlab.praguebest.cz/sylius/sylius-master/-/settings/ci_cd#js-runners-settings
        - runner2-docker

runBuild:
    stage: build
    variables:
        GIT_STRATEGY: none
    before_script:
        - eval $(ssh-agent -s)
        - ssh-add - <<< "${GITLAB_DEPLOY_GROUP_SYLIUS_SSH_KEY}"
        - ssh-keyscan "${DEPLOY_SERVER}" > /etc/ssh/ssh_known_hosts # to avoid "Host key verification failed." rsync/ssh error
    script:
        - ssh deployserver@$DEPLOY_SERVER "cd "${DEPLOY_LINKABLE_DIRECTORY}" && yarn install" #REMOVE IT
        # - ssh deployserver@$DEPLOY_SERVER "cd "${DEPLOY_LINKABLE_DIRECTORY}" && yarn install && yarn build:sylius && yarn cache clean --all" #UNCOMMENT IT
        - ssh deployserver@$DEPLOY_SERVER "cd "${DEPLOY_LINKABLE_DIRECTORY}"/../ && rm -rf "${APP_SUBPATH}" && ln -s "${DEPLOY_LINKABLE_PATH}" "${APP_SUBPATH}" && ls | grep -P "${DEPLOY_LINKABLE_PATH_PREFIX}__(?!"${CI_PIPELINE_ID}")" | xargs -d"\n" rm -rf"
        # - ssh deployserver@$DEPLOY_SERVER "sudo systemctl restart vuestorefront.praguebest.cz.service" #UNCOMMENT IT
        - rm --force --recursive $BUILD_CACHE_DIR_PROD
    # UNCOMMENT BELOW:
    # only:
    #     variables:
    #         - $CI_COMMIT_REF_NAME == $GIT_BRANCH
    tags:
        # runner has to be enabled https://gitlab.praguebest.cz/sylius/sylius-master/-/settings/ci_cd#js-runners-settings
        - runner2-docker
